[workspace]
members = [
    "src/abc/*",
    "src/arc/*",
    "src/ahc/*",
]
resolver = "2"

[workspace.dependencies]
proconio = "0.4.5"
itertools = "0.13.0"
superslice = "1.0.0"
num-integer = "0.1.44"