[package]
name = "atcoder-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
proconio = "0.4.5"
itertools = "0.13.0"
superslice = "1.0.0"

[[bin]]
name = "template"
path = "./template.rs"

[[bin]]
name = "abc001_a"
path = "./src/abc/001/a.rs"

[[bin]]
name = "abc001_b"
path = "./src/abc/001/b.rs"

[[bin]]
name = "abc001_c"
path = "./src/abc/001/c.rs"

[[bin]]
name = "abc001_d"
path = "./src/abc/001/d.rs"

[[bin]]
name = "abc001_e"
path = "./src/abc/001/e.rs"

[[bin]]
name = "abc001_f"
path = "./src/abc/001/f.rs"

[[bin]]
name = "abc001_g"
path = "./src/abc/001/g.rs"

[[bin]]
name = "abc002_a"
path = "./src/abc/002/a.rs"

[[bin]]
name = "abc002_b"
path = "./src/abc/002/b.rs"

[[bin]]
name = "abc002_c"
path = "./src/abc/002/c.rs"

[[bin]]
name = "abc002_d"
path = "./src/abc/002/d.rs"

[[bin]]
name = "abc002_e"
path = "./src/abc/002/e.rs"

[[bin]]
name = "abc002_f"
path = "./src/abc/002/f.rs"

[[bin]]
name = "abc002_g"
path = "./src/abc/002/g.rs"

[[bin]]
name = "abc427_a"
path = "./src/abc/427/a.rs"

[[bin]]
name = "abc427_b"
path = "./src/abc/427/b.rs"

[[bin]]
name = "abc427_c"
path = "./src/abc/427/c.rs"

[[bin]]
name = "abc427_d"
path = "./src/abc/427/d.rs"

[[bin]]
name = "abc427_e"
path = "./src/abc/427/e.rs"

[[bin]]
name = "abc427_f"
path = "./src/abc/427/f.rs"

[[bin]]
name = "abc427_g"
path = "./src/abc/427/g.rs"

[[bin]]
name = "abc42u_a"
path = "./src/abc/42u/a.rs"

[[bin]]
name = "abc42u_b"
path = "./src/abc/42u/b.rs"

[[bin]]
name = "abc42u_c"
path = "./src/abc/42u/c.rs"

[[bin]]
name = "abc42u_d"
path = "./src/abc/42u/d.rs"

[[bin]]
name = "abc42u_e"
path = "./src/abc/42u/e.rs"

[[bin]]
name = "abc42u_f"
path = "./src/abc/42u/f.rs"

[[bin]]
name = "abc42u_g"
path = "./src/abc/42u/g.rs"

[[bin]]
name = "abc428_a"
path = "./src/abc/428/a.rs"

[[bin]]
name = "abc428_b"
path = "./src/abc/428/b.rs"

[[bin]]
name = "abc428_c"
path = "./src/abc/428/c.rs"

[[bin]]
name = "abc428_d"
path = "./src/abc/428/d.rs"

[[bin]]
name = "abc428_e"
path = "./src/abc/428/e.rs"

[[bin]]
name = "abc428_f"
path = "./src/abc/428/f.rs"

[[bin]]
name = "abc428_g"
path = "./src/abc/428/g.rs"

[[bin]]
name = "abc426_a"
path = "./src/abc/426/a.rs"

[[bin]]
name = "abc426_b"
path = "./src/abc/426/b.rs"

[[bin]]
name = "abc426_c"
path = "./src/abc/426/c.rs"

[[bin]]
name = "abc426_d"
path = "./src/abc/426/d.rs"

[[bin]]
name = "abc426_e"
path = "./src/abc/426/e.rs"

[[bin]]
name = "abc426_f"
path = "./src/abc/426/f.rs"

[[bin]]
name = "abc426_g"
path = "./src/abc/426/g.rs"

[[bin]]
name = "abc425_a"
path = "./src/abc/425/a.rs"

[[bin]]
name = "abc425_b"
path = "./src/abc/425/b.rs"

[[bin]]
name = "abc425_c"
path = "./src/abc/425/c.rs"

[[bin]]
name = "abc425_d"
path = "./src/abc/425/d.rs"

[[bin]]
name = "abc425_e"
path = "./src/abc/425/e.rs"

[[bin]]
name = "abc425_f"
path = "./src/abc/425/f.rs"

[[bin]]
name = "abc425_g"
path = "./src/abc/425/g.rs"

[[bin]]
name = "abc433_a"
path = "./src/abc/433/a.rs"

[[bin]]
name = "abc433_b"
path = "./src/abc/433/b.rs"

[[bin]]
name = "abc433_c"
path = "./src/abc/433/c.rs"

[[bin]]
name = "abc433_d"
path = "./src/abc/433/d.rs"

[[bin]]
name = "abc433_e"
path = "./src/abc/433/e.rs"

[[bin]]
name = "abc433_f"
path = "./src/abc/433/f.rs"

[[bin]]
name = "abc433_g"
path = "./src/abc/433/g.rs"
